### ISSUE TITLE
Date and Time for Class

### ISSUE THREAD

**Issue by BrainBacon** [nodeschool/normal#1]
When is everyone available to meet during the week?

**Comment by shhonzi** [comment]
I'm free Monday and Wednesdays after 6:30. Tuesdays I am booked. I am free after normal work hours the rest of the week.

**Comment by punkadeedle** [comment]
I'm free Monday, Tuesday, Wednesday after 5.  Not available Thursdays.

**Comment by RestlessHobbyist** [comment]
Sign me up coach

**Comment by RyanInterr** [comment]
I'm free Monday or Wednesday after 5:30. Tuesday between 3 and 8

**Comment by codysherman** [comment]
I'm mostly free, except golly, am I booked on Tuesdays already after 7.

**Comment by bfrisch1** [comment]
Tuesday's 630 and Thursday's at 630 work best for me

**Comment by punkadeedle** [comment]
Hi all! Anyone who is interested in taking this class--click the link below and check all times that you would be available to attend on a weekly basis: http://doodle.com/poll/xhca2shnvhr3zkp6
Deadline: please submit by the end of Sunday (11/22)
