### ISSUE TITLE
Change Logo Colors

### ISSUE THREAD

**Issue by shhonzi** [nodeschool/normal#10]
To match the gh-pages website, we need to change the colors of the logo. Opening the .svg from the master branch wrecked formatting on the image and the font was all screwed up. 

I created a temporary logo with these colors for the interim, but I liked the font that Cristian used so I would just ask that he change the colors. Yellow should be #f7da03 and the black stroke should be #333333 (color of header). If that looks too light, use #222222 (color of the font).

Uploaded swatches to the master branch with these colors.

**Comment by RestlessHobbyist** [comment]
uploaded new svg and logo. No alt save forms available via inkscape so I'll have to convert the files if requested.

**Comment by shhonzi** [comment]
Looks good. Updated it on the site.
