### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by shhonzi** [nodeschool/normal#11]
Can anyone test the website on their phones and let me know the results? Reply back with any issues and model of the phone?

The flexbox layout I have for the .slingshot section of the site has the map loading over the slingshot info. This happens in Safari on iOS 6.

**Comment by punkadeedle** [comment]
Hey, looks awesome on my phone (Galaxy s6), everything seems to work. Nice job!!  Was a little confused with the wording here:  The meetups we hold are the workshops where workshoppers are used a curriculum...

**Comment by shhonzi** [comment]
closing due to lack of issue
