### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by BrainBacon** [nodeschool/normal#2]
[Here is the template for a code of conduct](https://github.com/nodeschool/organizers/blob/master/codeofconduct-template.md). If anyone has additions or suggestions please discuss it here!

**Comment by BrainBacon** [comment]
https://github.com/nodeschool/organizers/wiki/Code-of-Conduct-Creation

**Comment by shhonzi** [comment]
Cody finished the code of conduct and it is featured in the README of the master branch.
