### ISSUE TITLE
Chapter Logo

### ISSUE THREAD

**Issue by BrainBacon** [nodeschool/normal#3]
We're looking for people to modify the Nodeschool logo to be more "Normal" [Here's the details on the logo](https://github.com/nodeschool/organizers#make-a-logo).

**Comment by RestlessHobbyist** [comment]
First of our logo designs, feedback and bashing welcome.

If anything sticks out to you as saying "Normal" let me know and I will make a logo around that theme

![nodeschool](https://cloud.githubusercontent.com/assets/9053106/11229718/f3a9a234-8d5d-11e5-857a-8f4d9b6e5906.png)

**Comment by shhonzi** [comment]
Can you make the font [Source Sans Pro](https://www.google.com/fonts/specimen/Source+Sans+Pro) like it is featured on the nodeschool.io website and can you provide me with the color palate?

**Comment by RestlessHobbyist** [comment]
Here are a couple more designs, not in the Source Sans Pro font yet, will use that for the next set of logos. Idea is to take a vote next class on everyone's favorite for the page. 
![nodeschool2](https://cloud.githubusercontent.com/assets/9053106/11247064/259098c0-8de0-11e5-8ee3-67971bf53d8e.png)
![nodeschool3](https://cloud.githubusercontent.com/assets/9053106/11247065/2592e652-8de0-11e5-96df-47c3a6e7312d.png)

**Comment by shhonzi** [comment]
Anyone else getting a Tie Fighter vibe from Star Trek? I like the second one of the new post. The normal part of the original post adds a whole bunch of blank space.

**Comment by RestlessHobbyist** [comment]
haha that's exactly what I was thinking too, has a very space/ star wars kinda feel, also I dun goofed with the hexagon, it needs to be rotated to fit the nodeJS logo. So rotated hex, new font, and not a picture will be in the next design

**Comment by RestlessHobbyist** [comment]
new hex and pic, new font, and some color schemes for sampling.
![nodeschool4_black](https://cloud.githubusercontent.com/assets/9053106/11257056/06eaf520-8e15-11e5-8d6e-74d485c122d5.png)
![nodeschool4_blue](https://cloud.githubusercontent.com/assets/9053106/11257055/06ea0f20-8e15-11e5-9222-71ead05def32.png)
![nodeschool4_green](https://cloud.githubusercontent.com/assets/9053106/11257060/06ed98b6-8e15-11e5-95f9-a42eab755b3f.png)
![nodeschool4_orange](https://cloud.githubusercontent.com/assets/9053106/11257057/06eb6ba4-8e15-11e5-8ac2-a666e91d4f19.png)
![nodeschool4_purple](https://cloud.githubusercontent.com/assets/9053106/11257059/06ed782c-8e15-11e5-88b7-2dea04c579d8.png)
![nodeschool4_red](https://cloud.githubusercontent.com/assets/9053106/11257058/06ecc60c-8e15-11e5-85b2-f918ce901709.png)
![nodeschool4_yellow](https://cloud.githubusercontent.com/assets/9053106/11257061/06f4a37c-8e15-11e5-9fe3-caa04c3e451c.png)

**Comment by shhonzi** [comment]
I like the new hex better. This font only looks good without the color in my opinion, so I vote either solid black or use the original font with the new hex and make even more work for you.

**Comment by RestlessHobbyist** [comment]
Based on some feedback here's the latest batch. The one filled with no color/white is actually transparent so w.e color/pattern is behind it will be seen
![nodeschool4_black](https://cloud.githubusercontent.com/assets/9053106/11274214/42e0dc56-8e9d-11e5-8e7c-ebd6cdc20b00.png)
![nodeschool4_clear](https://cloud.githubusercontent.com/assets/9053106/11274217/42e2d128-8e9d-11e5-8c9e-578291110975.png)
![nodeschool4_indigo](https://cloud.githubusercontent.com/assets/9053106/11274213/42e014c4-8e9d-11e5-98e4-3c850f72b503.png)
![nodeschool4_orange](https://cloud.githubusercontent.com/assets/9053106/11274212/42de6872-8e9d-11e5-99a3-99f09e326b1c.png)
![nodeschool4_yellow](https://cloud.githubusercontent.com/assets/9053106/11274216/42e26198-8e9d-11e5-9311-a142a0f12b40.png)

**Comment by shhonzi** [comment]
Logo that was used was uploaded to the master branch.
